### ISSUE TITLE
Help with Docker

### ISSUE THREAD

**Issue by csandreas1** [DesignPatternsPHP/DesignPatternsPHP#486]
I am new to docker, after running docker-compose up --build, project is successfully built, however I am not able to find the created project files in order to be able to open the project in my IDE and run the tests.

I am using PHPstorm. Can anyone please explain the build process?

**Comment by domnikl** [comment]
Hi @csandreas1, you cannot run the tests in the container after it is build because it does not contain the PHP code. The container is only for viewing the documentation. However the tests are run in the process of building that container to ensure that the code is working correctly. You can see that `phpunit` runs in the Dockerfile: https://github.com/DesignPatternsPHP/DesignPatternsPHP/blob/main/Dockerfile#L10.

**Comment by csandreas1** [comment]
I got confused because the docker file is inside the repository of the project with the PHP code. Perhaps an update on the documentation here could make things more clearer of the docker setup and purpose.
