### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by GE08T** [DesignPatternsPHP/DesignPatternsPHP#501]
can i make this to my language as pull request??

**Comment by BorislavSabev** [comment]
Yes, of course you can. You can easily add a translation by adding the required locale folder & files structure.
However I would advise against that at the current moment as we are considering dropping the multiple language support.

The main problem is that people who do translations generally do it once and forget about it. However this repository is evolving and is changing constantly. Thus the translations are lagging behind the original English version.

Web translation tools are good enough now so that we don't need to support multiple translations in the repository.
